### ISSUE TITLE
Feature Request: Set up using Storyboard

### ISSUE THREAD

**Issue by randyhbh** [kirankunigiri/SVUploader#1]
Will be a nice feature

**Comment by kirankunigiri** [comment]
Hi! Storyboard setup is already supported. You can see an example in the demo project, where there are already 2 view controllers: `CodeViewController` and `StoryboardViewController`. You can take a look at `StoryboardViewController` to see how to set it up.

 It's really simple - just drag a UIView to the storyboard and set the subclass to `SVUploader`. Then, connect it as an outlet and you can use it normally in the view controller file. I'll probably add this to the README so that people know it's already supported.

**Comment by randyhbh** [comment]
Thanks for the explanation, and yes you should add it to the README. Regards.

BTW: Great Job
